"""
Database models for SaaS-style setup.
Currently: single-user-friendly (no auth yet), but structured for future multi-user.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Dict

from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()


class User(UserMixin, db.Model):
    """User account model for authentication."""

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=True)
    google_api_key = db.Column(db.String(255))
    deepseek_api_key = db.Column(db.String(255))
    linkedin_url = db.Column(db.String(512))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # Relationships
    profile = db.relationship("Profile", back_populates="user", uselist=False)
    applications = db.relationship("JobApplication", back_populates="user", lazy=True)

    @classmethod
    def get_by_email(cls, email: str) -> "User | None":
        return cls.query.filter_by(email=email.lower().strip()).first()

    @classmethod
    def create(cls, email: str, password_hash: str) -> "User":
        user = cls(email=email.lower().strip(), password_hash=password_hash)
        db.session.add(user)
        db.session.commit()
        return user


class Profile(db.Model):
    """Profile data stored per user (or single system profile if no auth)."""

    __tablename__ = "profiles"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    # Store profile as JSON blob for flexibility
    data = db.Column(db.JSON, nullable=False, default=dict)

    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    user = db.relationship("User", back_populates="profile")

    @staticmethod
    def get_singleton_profile() -> "Profile":
        """Get or create a singleton profile."""
        profile = Profile.query.first()
        if not profile:
            profile = Profile(data={})
            db.session.add(profile)
            db.session.commit()
        return profile

    @staticmethod
    def get_or_create_for_user(user_id: int) -> "Profile":
        """Get or create a profile for a specific user."""
        profile = Profile.query.filter_by(user_id=user_id).first()
        if not profile:
            profile = Profile(user_id=user_id, data={})
            db.session.add(profile)
            db.session.commit()
        return profile

    def to_dict(self) -> Dict[str, Any]:
        return self.data or {}

    def update_from_dict(self, new_data: Dict[str, Any]) -> None:
        self.data = new_data
        db.session.add(self)
        db.session.commit()


class JobApplication(db.Model):
    """Tracks individual job applications generated by the user."""

    __tablename__ = "job_applications"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    
    role_title = db.Column(db.String(255))
    company = db.Column(db.String(255))
    match_score = db.Column(db.Float)
    
    # Store files or paths
    cv_path = db.Column(db.String(512))
    cover_letter_path = db.Column(db.String(512))
    
    # Store technical data
    analysis_data = db.Column(db.JSON)
    status = db.Column(db.String(50), default="pending") # pending, processing, completed, failed
    error_message = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship("User", back_populates="applications")

    @classmethod
    def create(cls, user_id, role_title=None, company=None, match_score=0, cv_path=None, cover_letter_path=None, analysis_data=None, status="pending"):
        app = cls(
            user_id=user_id,
            role_title=role_title,
            company=company,
            match_score=match_score,
            cv_path=cv_path,
            cover_letter_path=cover_letter_path,
            analysis_data=analysis_data,
            status=status
        )
        db.session.add(app)
        db.session.commit()
        return app


def init_db(app) -> None:
    """Initialize SQLAlchemy with the Flask app."""
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        database_url = "sqlite:///app.db"

    app.config["SQLALCHEMY_DATABASE_URI"] = database_url
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    db.init_app(app)

    with app.app_context():
        db.create_all()

